import { useMemo } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { trpc } from '@/utils/trpc';

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(['get-search-position', { query: 'You Tube' }]);

  const renderResoultsList = useMemo(() => data?.map(({ link }) => <li key={link}>{link}</li>), [data]);

  return (
    <section>
      <Head>
        <title>SEO Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Hello World.</p>

      {isLoading ? <span>Loading</span> : renderResoultsList}
    </section>
  );
};

export default Home;
